powerlevel9k_random_color(){
    printf "%03d" $[${RANDOM}%234+16] #random between 16-250
}

#DEFAULT_USER=$USER

# Easily switch primary foreground/background colors
#DEFAULT_FOREGROUND=038 DEFAULT_BACKGROUND=024 PROMPT_COLOR=038

DEFAULT_FOREGROUND=006 DEFAULT_BACKGROUND=235 PROMPT_COLOR=173
DEFAULT_FOREGROUND=198 DEFAULT_BACKGROUND=090 PROMPT_COLOR=173
DEFAULT_FOREGROUND=235 DEFAULT_BACKGROUND=159 PROMPT_COLOR=173
DEFAULT_FOREGROUND=123 DEFAULT_BACKGROUND=059 PROMPT_COLOR=183
DEFAULT_FOREGROUND=159 DEFAULT_BACKGROUND=238 PROMPT_COLOR=173
DEFAULT_FOREGROUND=159 DEFAULT_BACKGROUND=239 PROMPT_COLOR=172
#DEFAULT_COLOR=$DEFAULT_FOREGROUND
DEFAULT_COLOR="clear"

POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_DIR_SHORTEN_LENGTH=1
#POWERLEVEL9K_SHORTEN_STRATEGY="truncate_right"

POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=false

POWERLEVEL9K_CONTEXT_ALWAYS_SHOW=true
POWERLEVEL9K_CONTEXT_ALWAYS_SHOW_USER=false

#POWERLEVEL9K_CONTEXT_TEMPLATE="\uF109 %m"

#POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR="%F{$(( $DEFAULT_BACKGROUND - 2 ))}|%f"
#POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR="%F{$(( $DEFAULT_BACKGROUND - 2 ))}|%f"

#POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR="%F{$DEFAULT_BACKGROUND}\ue0b0%f"
#POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR="%F{$DEFAULT_BACKGROUND}\ue0b2%f"
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR_ICON="%F{232}\uE0BD%f"
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR_ICON="%F{232}\uE0BD%f"
#POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR="%F{000}%f"
#POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR="%F{000}／%f" # 
#POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR="%F{000}／%f" #
#POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR="%F{$(( $DEFAULT_BACKGROUND - 3 ))}／%f"
#POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR="%F{$(( $DEFAULT_BACKGROUND - 3 ))}／%f"
#POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR="%F{$DEFAULT_FOREGROUND}\uE0B0%f"
#POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR="%F{$DEFAULT_FOREGROUND}\uE0B3%f"

#POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR="\uE0B4"
#POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR="\uE0B6"
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR_ICON='▓▒░'
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR_ICON='░▒▓'
#POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR="\uE0BC\u200A"
#POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR="\u200A\uE0BA"
#POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR="\uE0BC"
#POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR="\uE0BA"
#POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR="%F{$DEFAULT_BACKGROUND}\uE0BC%f"
#POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR="%F{$DEFAULT_BACKGROUND}\uE0BA%f"

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_RPROMPT_ON_NEWLINE=false

POWERLEVEL9K_STATUS_VERBOSE=true
POWERLEVEL9K_STATUS_CROSS=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX_ICON="%F{$PROMPT_COLOR}%f"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX_ICON="%F{$PROMPT_COLOR}➜ %f"
#POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX_ICON="%F{$PROMPT_COLOR}⇢ ➜  %f"
#POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX_ICON="%F{$PROMPT_COLOR} ┄⇢ %f"

# POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon context dir_writable dir vcs)
# POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs time ssh)

#POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon context dir_writable dir_joined vcs)
#POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir_writable dir_joined vcs)
#POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator exec_time background_jobs time)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon context dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs command_execution_time time)

POWERLEVEL9K_MODE='nerdfont-complete'

POWERLEVEL9K_VCS_GIT_GITHUB_ICON=""
POWERLEVEL9K_VCS_GIT_BITBUCKET_ICON=""
POWERLEVEL9K_VCS_GIT_GITLAB_ICON=""
POWERLEVEL9K_VCS_GIT_ICON=""

POWERLEVEL9K_VCS_CLEAN_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_VCS_CLEAN_FOREGROUND="010"

POWERLEVEL9K_VCS_MODIFIED_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="011"

POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND="$DEFAULT_BACKGROUND"
#POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="012"
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="011"

POWERLEVEL9K_DIR_HOME_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_DIR_HOME_FOREGROUND="158"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="158"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND="$DEFAULT_BACKGROUND"
#POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="red"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="158"
POWERLEVEL9K_DIR_ETC_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_DIR_ETC_FOREGROUND="158"
POWERLEVEL9K_DIR_NOT_WRITABLE_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_DIR_NOT_WRITABLE_FOREGROUND="158"

POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND="red"

POWERLEVEL9K_STATUS_OK_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_STATUS_OK_FOREGROUND="green"
POWERLEVEL9K_STATUS_ERROR_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="red"

#POWERLEVEL9K_TIME_FORMAT="%D{%H:%M:%S \uf017}" #  Jun 15  09:32
POWERLEVEL9K_TIME_ICON="\uF017" # 
#POWERLEVEL9K_TIME_BACKGROUND="$(( $DEFAULT_BACKGROUND - 2 ))"
POWERLEVEL9K_TIME_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_TIME_FOREGROUND="183"

POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND="$DEFAULT_BACKGROUND"
#POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND="183"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=1

POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND="123"

POWERLEVEL9K_USER_DEFAULT_BACKGROUND="$DEFAULT_BACKGROUND"
#POWERLEVEL9K_USER_DEFAULT_FOREGROUND="cyan"
POWERLEVEL9K_USER_SUDO_BACKGROUND="$DEFAULT_BACKGROUND"
#POWERLEVEL9K_USER_SUDO_FOREGROUND="magenta"
POWERLEVEL9K_USER_ROOT_BACKGROUND="$DEFAULT_BACKGROUND"
#POWERLEVEL9K_USER_ROOT_FOREGROUND="red"
POWERLEVEL9K_USER_DEFAULT_ICON="\uF415" # 
POWERLEVEL9K_USER_ROOT_ICON=$'\uFF03' # ＃

POWERLEVEL9K_CONTEXT_TEMPLATE="\uF109 %m"
#POWERLEVEL9K_CONTEXT_TEMPLATE="\uF109 %m"
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND="$DEFAULT_BACKGROUND"
#POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="$DEFAULT_FOREGROUND"
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND="123"
POWERLEVEL9K_CONTEXT_SUDO_BACKGROUND="$DEFAULT_BACKGROUND"
#POWERLEVEL9K_CONTEXT_SUDO_FOREGROUND="$DEFAULT_FOREGROUND"
POWERLEVEL9K_CONTEXT_SUDO_FOREGROUND="123"
POWERLEVEL9K_CONTEXT_REMOTE_BACKGROUND="$DEFAULT_BACKGROUND"
#POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND="$DEFAULT_FOREGROUND"
POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND="123"
POWERLEVEL9K_CONTEXT_REMOTE_SUDO_BACKGROUND="$DEFAULT_BACKGROUND"
#POWERLEVEL9K_CONTEXT_REMOTE_SUDO_FOREGROUND="$DEFAULT_FOREGROUND"
POWERLEVEL9K_CONTEXT_REMOTE_SUDO_FOREGROUND="123"
POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND="$DEFAULT_BACKGROUND"
#POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND="$DEFAULT_FOREGROUND"
POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND="123"

POWERLEVEL9K_HOST_LOCAL_BACKGROUND="$DEFAULT_BACKGROUND"
#POWERLEVEL9K_HOST_LOCAL_FOREGROUND="cyan"
POWERLEVEL9K_HOST_REMOTE_BACKGROUND="$DEFAULT_BACKGROUND"
#POWERLEVEL9K_HOST_REMOTE_FOREGROUND="magenta"
POWERLEVEL9K_HOST_LOCAL_ICON="\uF109 " # 
POWERLEVEL9K_HOST_REMOTE_ICON="\uF489 "  # 

POWERLEVEL9K_SSH_ICON="\uF489 "  # 
#POWERLEVEL9K_SSH_BACKGROUND="$(( $DEFAULT_BACKGROUND - 2 ))"
POWERLEVEL9K_SSH_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_SSH_FOREGROUND="212"
#POWERLEVEL9K_OS_ICON_BACKGROUND="$(( $DEFAULT_BACKGROUND - 2 ))"
POWERLEVEL9K_OS_ICON_BACKGROUND="$DEFAULT_BACKGROUND"
POWERLEVEL9K_OS_ICON_FOREGROUND="212"
#POWERLEVEL9K_SHOW_CHANGESET=true

P9K_IGNORE_VAR_WARNING=true