#!/bin/bash

## Created By Aditya Shakya

rofi -modi run,drun -show drun -location 1 -xoffset 5 -yoffset 30 -line-padding 3 -columns 1 \
     -width 20 -lines 12 -padding 25 -hide-scrollbar -show-icons -drun-icon-theme
